blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

        # Example:/blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example:/blog/post/(sameas/blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example:/blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example:/blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example:/blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example:/blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example:/blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example:/blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example:/blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name="add"),
    path('change/', views.PostChangeLV.as_view(), name="change"),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(),name='register'),
    path('acounts/register/done/', UserCreateDoneTV.as_view(),name='register_done'),


    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('namecard/', include('namecard.urls')),
    path('student/', include('student.urls')),
    path('photo1/', include('photo1.urls')),
    path('sugang/', include('sugang.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #static함수는 정적파일을 처리하기위한 url패턴을 반환

sugang/urls.py
from django.urls import path
from sugang import views


app_name = 'sugang'
urlpatterns = [

    # Example: /sugang
    path('', views.SubjectLV.as_view(), name='index'),

    # Example: /sugang/subject/, same as /apply/
    path('subject', views.SubjectLV.as_view(), name='subject_list'),

    # Example:/sugang/subject/99/
    path('subject/<int:pk>/', views.SubjectDV.as_view(), name='subject_detail'),

    # Example: /sugang/apply/99/
    path('apply/<int:pk>/', views.ApplyDV.as_view(), name='apply_detail'),

    # Example: /photo/album/add/
    path('subject/add/', views.SubjectApplyCV.as_view(), name='subject_add'),

    # Example: /photo/album/change/
    path('subject/change/', views.SubjectChangeLV.as_view(), name='subject_change'),

    # Example: /photo/album/99/update/
    path('subject/<int:pk>/update/', views.SubjectApplyUV.as_view(), name='subject_update'),

    # Example: /photo/album/99/delete/
    path('subject/<int:pk>/delete/', views.SubjectDelV.as_view(), name='subject_delete'),

    # Example: /photo/photo/add/
    path('apply/add/', views.ApplyCV.as_view(), name='apply_add'),

    # Example: /photo/photo/change/
    path('apply/change/', views.ApplyChangeLV.as_view(), name='apply_change'),

    # Example: /photo/photo/99/update/
    path('apply/<int:pk>/update/', views.ApplyUV.as_view(), name='apply_update'),

    # Example: /photo/photo/99/delete/
    path('apply/<int:pk>/delete/', views.ApplyDelV.as_view(), name='apply_delete'),

]

sugang/models.py
from django.db import models
from django.urls import reverse


class Subject(models.Model):
    name = models.CharField('NAME', max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sugang:subject_detail', args=(self.id,))


class Apply(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    name = models.CharField('NAME', max_length=20)
    number = models.CharField('NUMBER', max_length=20)
    major = models.CharField('MAJOR', max_length=20) #upload_to 이미지가 저장될 폴더
    upload_dt = models.DateTimeField('UPDATE DATE', auto_now_add=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)  # 추가①

    class Meta:
        ordering = ('subject',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sugang:apply_detail', args=(self.id,))

sugang/forms.py
from django.forms import inlineformset_factory
from sugang.models import Subject, Apply

SubjectInlineFormSet = inlineformset_factory(Subject, Apply, fields=['name', 'number', 'major'], extra=2)

sugang/views.py
from django.views.generic import ListView, DetailView
from sugang.models import Subject, Apply
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from mysite.views import OwnerOnlyMixin
from sugang.forms import SubjectInlineFormSet

class SubjectLV(ListView):
    model = Subject


class SubjectDV(DetailView):
    model = Subject


class ApplyDV(DetailView):
    model = Apply


class ApplyCV(LoginRequiredMixin, CreateView):
    model = Apply
    fields = ('subject', 'name', 'number', 'major')
    success_url = reverse_lazy('sugang:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ApplyChangeLV(LoginRequiredMixin, ListView):
    model = Apply
    template_name = 'sugang/apply_change_list.html'

    def get_queryset(self):
        return Apply.objects.filter(owner=self.request.user)


class ApplyUV(OwnerOnlyMixin, UpdateView):
    model = Apply
    fields = ('subject', 'name', 'number', 'major')
    success_url = reverse_lazy('sugang:index')


class ApplyDelV(OwnerOnlyMixin, DeleteView):
    model = Apply
    success_url = reverse_lazy('sugang:index')

#이하추가
# #---Change-list/Delete for Album


class SubjectChangeLV(LoginRequiredMixin, ListView):
    model = Subject
    template_name = 'sugang/subject_change_list.html'

    def get_queryset(self):
        return Subject.objects.filter(owner=self.request.user)


class SubjectDelV(OwnerOnlyMixin, DeleteView):
    model = Subject
    success_url = reverse_lazy('sugang:index')


#---(InlineFormSet) Create/Update for Album


class SubjectApplyCV(LoginRequiredMixin, CreateView):
    model = Subject
    fields = ('name', 'description')   #어떤 컬럼을 폼에 채울지.
    success_url = reverse_lazy('sugang:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = SubjectInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = SubjectInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for applyform in formset:
            applyform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()   #앨범 레코드 생성.
            formset.instance = self.object #포토의 앨범컬럼에 앪범레코드의 id값을 설정
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class SubjectApplyUV(OwnerOnlyMixin, UpdateView):
    model = Subject
    fields = ('name', 'description')
    success_url = reverse_lazy('sugang:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = SubjectInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = SubjectInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

sugang/templates/sugang/apply_change_list.html
{% extends "base.html" %}
{% block title %}photo_change_list.html{% endblock %}
{% block content %}
    <h1>Apply Change -{{user}}</h1>
    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="table-info">
            <th>Subject</th>
            <th>Name</th>
            <th>Number</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.subject }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.number }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'sugang:apply_update' item.id %}">Update</a></td>
            <td><a href="{% url 'sugang:apply_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

sugang/templates/sugang/apply_confirm_delete.html
{% extends "base.html" %}
{% block title %}photo_confirm_delete.html{% endblock %}
{% block content %}
<h1>Photo Delete</h1>
<br>
<form action="." method="post">{% csrf_token %}<p>
    Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
</form>
{% endblock %}

sugang/templates/sugang/apply_detail.html
{% extends "base.html" %}
{% block title %}apply_detail.html{% endblock %}
{% block content %}

    <h2 class="mt-5">{{ object.title }}</h2>
    <div class="row">

        <ul class="col-md-3 mt-3">
            <li class="h5">Student Information</li>
            {% if object.name %}
            <p>이름: {{object.name}}</p>
            <p>학과: {{ object.major}}</p>
            <p>학번: {{object.number}}</p>
            {% else %}<p>(blank)</p>{% endif %}

            <li class="h5">Apply Date</li>
                <p class="font-italic">{{ object.upload_dt }}</p>
            <li class="h5">Subject Name</li>
                <p class="font-italic">
                    <a href="{% url 'sugang:subject_detail' object.subject.id %}"> {{ object.subject.name }}</a>
                </p>
        </ul>
    </div>

{% endblock %}

sugang/templates/sugang/apply_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Apply_form.html{% endblock %}
{% block content %}
    <h1>Apply Create/Update -{{user}}</h1>
    <p class="font-italic">This is a creation or update form for your apply.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    {% if form.is_multipart %}
    <form enctype="multipart/form-data" action="" method="post" class="card pt-3">{% csrf_token %}
    {% else %}
    <form action="." method="post" class="card pt-3">{% csrf_token %}
    {% endif %}



        <div class="form-group row">
            {{ form.subject|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-2">
                {{ form.subject|add_class:"form-control" }}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'sugang:subject_add' %}" class="btn btn-outline-primary btn-sm">Add Album</a>
            </div>
        </div>

        <div class="form-group row">
            {{ form.name|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.name|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.number|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.number|add_class:"form-control" }}
            </div>
        </div>

         <div class="form-group row">
              {{ form.major|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
              <div class="col-sm-5">
                 {{ form.major|add_class:"form-control"}}
             </div>
         </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
             </div>
        </div>
    </form>
{% endblock %}

sugang/templates/sugang/subject_change_list.html
{% extends "base.html" %}
{% block title %}album_change_list.html{% endblock %}
{% block content %}

    <h1>Subject Change -{{user}}</h1>
    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="table-success">
            <th>Name</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'sugang:subject_update' item.id %}">Update</a></td>
            <td><a href="{% url 'sugang:subject_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

sugang/templates/sugang/subject_confirm_delete.html
{% extends "base.html" %}
{% block title %}album_confirm_delete.html{% endblock %}
{% block content %}
    <h1>Album Delete <small class="font-italic">(including related photos)</small></h1>

    <br>
    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}

sugang/templates/sugang/subject_detail.html
{% extends "base.html" %}
{% block title %}subject_detail.html{% endblock %}
{% block extra-style %}
<style>
.thumbnail {
border: 2px solid #ff9999;
}</style>

{% endblock %}
{% block content %}
    <div class="mt-5">
        <span class="h2">{{ object.name }}&emsp;</span>
        <span class="h5 font-italic">{{ object.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">
    <div class="row">
        {% for apply in object.apply_set.all %}
        <div class="col-md-3 mb-5">
            <div class="thumbnail">
                <a href="{{ apply.get_absolute_url }}">{{apply.name}}</a>
                <ul>
                    <li class="font-italic">학번: {{ apply.number }}</li>
                    <li class="font-italic">학과: {{ apply.major }}</li>

                    <li class="font-italic">수강신청일: {{ apply.upload_dt|date:"Y-m-d" }}</li>
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

sugang/templates/sugang/subject_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}album_form.html{% endblock %}

{% block content %}
    <h1>Subject-Apply Create/Update -{{user}}</h1>
    <p class="font-italic">This is a creation or update form for your album using PhotoInlineFormSet.</p>
    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    {% if formset.errors %}
    <div class="alert alert-warning">
        <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
        {% for formerrors in formset.errors %}
            {{ formerrors }}
        {% endfor %}
    </div>
    {% endif %}

    {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" action="" method="post">
    {% else %}
    <form action="." method="post">
    {% endif %}
    {% csrf_token %}

    <h4>create or update Subject contents</h4>
    <fieldset class="card pt-3">
        <div class="form-group row">
            {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.name|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control" }}
            </div>
        </div>
    </fieldset>
    <br>

    <h4>create or update Apply contents</h4>
    <fieldset class="card pt-3">
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.id }}
            {# form.subject #}
        <div class="form-group row">
            {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.name|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.number|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.number|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.major|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.major|add_class:"form-control"}}</br>
            </div>
        </div><hr>{% endfor %}
    </fieldset>
        <div class="form-group card py-1">
            <div class="offset-sm-3 col-sm-5"><input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>
    </form>
{% endblock %}

sugang/templates/sugang/subject_list.html
{% extends "base.html" %}
{% block title %}subject_list.html{% endblock %}
{% block extra-style %}

<style>
.thumbnail {
border: 2px solid #ff9999;
padding: 0 25px 0 0;
}
</style>

{% endblock %}

{% block content %}

    {% for item in object_list %}
    <div class="mt-5">
        <a class="h2" href="{% url 'sugang:subject_detail' item.id %}">
            {{ item.name }}</a>&emsp;
        <span class="font-italic h5">{{ item.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">

    <div class="row">
        {% for apply in item.apply_set.all|slice:":5" %}
        <div class="ml-5">
            <div class="thumbnail">
                <a href="{{ apply.get_absolute_url }}">
-                       {{apply.name}}
                </a>
                    <ul>
                        학과: {{ apply.major}}<br/>
                        학번: {{apply.number}}
                    </ul>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% endblock %}