blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

        # Example:/blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example:/blog/post/(sameas/blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example:/blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example:/blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example:/blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example:/blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example:/blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example:/blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example:/blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name="add"),
    path('change/', views.PostChangeLV.as_view(), name="change"),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(),name='register'),
    path('acounts/register/done/', UserCreateDoneTV.as_view(),name='register_done'),


    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('namecard/', include('namecard.urls')),
    path('student/', include('student.urls')),
    path('photo1/', include('photo1.urls')),
    path('sugang/', include('sugang.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #static함수는 정적파일을 처리하기위한 url패턴을 반환

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')  #디자인 말고 규격만

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic import DayArchiveView, TodayArchiveView
from blog.models import Post

from django.views.generic import FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin


# ---ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

# ---DetailView
class PostDV(DetailView):
    model = Post

# ---ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'


class SearchFormView(FormView):  #사용자가 입력한 값을 포스트/겟방식으로 처리해서 액션
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(Q(title__icontains=searchWord) |
                                        Q(description__icontains=searchWord) |
                                        Q(content__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)



# 하단4개의클래스형뷰추가
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content']
    initial = {'slug':'auto-filling-do-not-input'}
    #fields = ['title', 'description', 'content']
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content']
    success_url = reverse_lazy('blog:index')


class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
{% extends "base.html" %}
{% block title %} post_all.html {% endblock %}
{% block content %}


<h1>BlogList</h1>
<br>

{% for post in posts %}
    <h3><a href='{{ post.get_absolute_url }}'>{{post.title}}</a></h3>
    {{post.modify_dt|date:"N d, Y"}}
    <p>{{post.description}}</p>
{%endfor%}
<br>

<div>
    <span>
        {% if page_obj.has_previous %}
         <a href="?page={{page_obj.previous_page_number}}">PreviousPage</a>
        {%endif%}
        Page{{page_obj.number}} of {{page_obj.paginator.num_pages}}
        {%if page_obj.has_next%}
            <a href="?page={{page_obj.next_page_number}}">NextPage</a>
        {%endif%}
    </span>
</div>

{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}
{% block title %} post_archive.html {% endblock %}
{% block content %}


<h1>Post Archives until{%now "N d, Y"%}</h1>
<ul>
    {%for date in date_list%}
    <li style="display:inline;">
        <a href="{%url 'blog:post_year_archive' date|date:'Y'%}">Year-{{date|date:"Y"}}</a></li>
    {%endfor%}
</ul>
<br/>

<div>
    <ul>
        {%for post in object_list%}
        <li>{{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
        <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a></li>
        {%endfor%}
    </ul>
</div>

{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}
{% block title %} post_archive_day.html {% endblock %}
{% block content %}


<h1>Post Archives for{{day|date:"Nd,Y"}}</h1>
<div>
    <ul>
        {%for post in object_list%}
        <li>{{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a></li>
        {%endfor%}
    </ul>
</div>


{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}
{% block title %} post_archive_month.html {% endblock %}
{% block content %}


<h1>Post Archives for{{month|date:"N, Y"}}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_day_archive' date|date:'Y' date|date:'b' date|date:'d'%}">{{ date|date:"d"}}</a></li>
    {% endfor %}
</ul>



<div>
    <ul>
        {%for post in object_list%}
        <li>{{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a></li>
        {%endfor%}
    </ul>
</div>

{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}
{% block title %} post_archive_year.html {% endblock %}
{% block content %}


<h1>Post Archives for {{year|date:"Y"}}</h1>
<ul>
    {%for date in date_list%}
    <li style="display:inline;">
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a></li>
    {% endfor %}
</ul>
<br>

<div>
    <ul>
        {%for post in object_list%}
        <li>{{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
        <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a></li>
        {%endfor%}
    </ul>
</div>

{% endblock %}

blog/templates/blog/post_change_list.html
{% extends "base.html" %}
{% block title %}post_change_list.html{% endblock %}
{% block content %}


    <h1>Post Change -{{user}}</h1>
    <br>

    <table class="table table-bordered table-sm table-striped">

        <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
            <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>

    </table>


{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}post_confirm_delete.html{% endblock %}
{% block content %}

    <h1>Post Delete</h1>
    <br>

    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% block title %} post_detail.html {% endblock %}
{% block content %}


<h2>{{object.title}}</h2>
<p>
    {%if object.get_previous%}
    <a href="{{object.get_previous.get_absolute_url}}" title="View previous post">
        &laquo;--{{object.get_previous}}
    </a>
    {%endif%}

    {%if object.get_next%}
    |<a href="{{object.get_next.get_absolute_url}}"title="View next post">
    {{object.get_next}}--&raquo;
    </a>
    {%endif%}
</p>

<p>{{object.modify_dt|date:"j F Y"}}</p>
<br>

<div>
    {{object.content|linebreaks}}
</div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}post_form.html{% endblock %}

{% block content %}
    <h1>Post Create/Update -{{user}}</h1>
    <p class="font-italic">This is a creation or update form for your post.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}
        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">{{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">{{ form.slug|add_class:"form-control"|attr:"readonly" }}</div>
            <small class="form-text text-muted">{{ form.slug.help_text }}</small>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">{{ form.description|add_class:"form-control" }}</div>
            <small class="form-text text-muted"></small>
        </div>

        <div class="form-group row">
            {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">{{ form.content|add_class:"form-control" }}</div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>

    </form>


{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}

    <h1>Blog Search</h1>
    <br>
    <!-- form 생성 액션에서 . 은 이페이지를 그대로 불러들음 즉 blog/post/post_search라는 요청이 전송 리다이렉트-->
    <form action="." method="post"> {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>
    <br/><br/>
    {% if object_list %}
        {% for post in object_list %}
        <h2><a href="{{ post.get_absolute_url}}">{{post.title}}</a></h2>
        {{ post.modify_dt|date:"N d, Y" }}
        <p>{{ post.description}}</p>
        {% endfor %}
    {% elif search_term %}
    <b><i>Search Word({{ search_term}}) Not Found!</i></b>
    {% endif %}
{% endblock %}