blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

        # Example:/blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example:/blog/post/(sameas/blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example:/blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example:/blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example:/blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example:/blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example:/blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example:/blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example:/blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name="add"),
    path('change/', views.PostChangeLV.as_view(), name="change"),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete"),
]

bookmark/urls.py
from django.urls import path

from bookmark import views



app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    # Example:/blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.BookmarkCreateView.as_view(), name="add"),
    path('change/', views.BookmarkChangeLV.as_view(), name="change"),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(),name='register'),
    path('acounts/register/done/', UserCreateDoneTV.as_view(),name='register_done'),


    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('namecard/', include('namecard.urls')),
    path('student/', include('student.urls')),
    path('photo1/', include('photo1.urls')),
    path('sugang/', include('sugang.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #static함수는 정적파일을 처리하기위한 url패턴을 반환

photo1/urls.py
from django.urls import path
from photo1 import views


app_name = 'photo1'
urlpatterns = [

    # Example: /photo/
    path('', views.AlbumLV.as_view(), name='index'),

    # Example: /photo/album/, same as /photo/
    path('album1', views.AlbumLV.as_view(), name='album1_list'),

    # Example: /photo/album/99/
    path('album1/<int:pk>/', views.AlbumDV.as_view(), name='album1_detail'),

    # Example: /photo/photo/99/
    path('photo1/<int:pk>/', views.PhotoDV.as_view(), name='photo1_detail'),

    # Example: /photo/album/add/
    path('album1/add/', views.AlbumPhotoCV.as_view(), name='album1_add'),

    # Example: /photo/album/change/
    path('album1/change/', views.AlbumChangeLV.as_view(), name='album1_change'),

    # Example: /photo/album/99/update/
    path('album1/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album1_update'),

    # Example: /photo/album/99/delete/
    path('album1/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album1_delete'),

    # Example: /photo/photo/add/
    path('photo1/add/', views.PhotoCV.as_view(), name='photo1_add'),

    # Example: /photo/photo/change/
    path('photo1/change/', views.PhotoChangeLV.as_view(), name='photo1_change'),

    # Example: /photo/photo/99/update/
    path('photo1/<int:pk>/update/', views.PhotoUV.as_view(), name='photo1_update'),

    # Example: /photo/photo/99/delete/
    path('photo1/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo1_delete'),

]

student/urls.py
from django.urls import path
from student.views import StudentLV, StudentDV,SearchFormView
from student import views

app_name = 'student'
urlpatterns = [
    path('', StudentLV.as_view(), name='index'),
    path('<int:pk>/', StudentDV.as_view(), name='detail'),
    path('search/', SearchFormView.as_view(), name='search'),
    path('add/', views.StudentCreateView.as_view(), name="add"),
    path('change/', views.StudentChangeLV.as_view(), name="change"),
    path('<int:pk>/update/', views.StudentUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.StudentDeleteView.as_view(), name="delete"),
]

sugang/urls.py
from django.urls import path
from sugang import views


app_name = 'sugang'
urlpatterns = [

    # Example: /sugang
    path('', views.SubjectLV.as_view(), name='index'),

    # Example: /sugang/subject/, same as /apply/
    path('subject', views.SubjectLV.as_view(), name='subject_list'),

    # Example:/sugang/subject/99/
    path('subject/<int:pk>/', views.SubjectDV.as_view(), name='subject_detail'),

    # Example: /sugang/apply/99/
    path('apply/<int:pk>/', views.ApplyDV.as_view(), name='apply_detail'),

    # Example: /photo/album/add/
    path('subject/add/', views.SubjectApplyCV.as_view(), name='subject_add'),

    # Example: /photo/album/change/
    path('subject/change/', views.SubjectChangeLV.as_view(), name='subject_change'),

    # Example: /photo/album/99/update/
    path('subject/<int:pk>/update/', views.SubjectApplyUV.as_view(), name='subject_update'),

    # Example: /photo/album/99/delete/
    path('subject/<int:pk>/delete/', views.SubjectDelV.as_view(), name='subject_delete'),

    # Example: /photo/photo/add/
    path('apply/add/', views.ApplyCV.as_view(), name='apply_add'),

    # Example: /photo/photo/change/
    path('apply/change/', views.ApplyChangeLV.as_view(), name='apply_change'),

    # Example: /photo/photo/99/update/
    path('apply/<int:pk>/update/', views.ApplyUV.as_view(), name='apply_update'),

    # Example: /photo/photo/99/delete/
    path('apply/<int:pk>/delete/', views.ApplyDelV.as_view(), name='apply_delete'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'photo1:index' %}">Photo</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'namecard:index' %}">Namecard</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'student:index' %}">Student</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'sugang:index' %}">Sugang</a></li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                    <a class="dropdown-item" href="{% url 'bookmark:search' %}">Bookmark Search</a>
                    <a class="dropdown-item" href="{% url 'blog:search' %}">Blog Search</a>
                    <a class="dropdown-item" href="{% url 'namecard:search' %}">Namecard Search</a>
                    <a class="dropdown-item" href="{% url 'student:search' %}">Student Search</a>
                </div>
            </li>



            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
                    <a class="dropdown-item" href="{% url 'blog:add' %}">Blog</a>
                    <a class="dropdown-item" href="{% url 'namecard:add' %}">Namecard</a>
                    <a class="dropdown-item" href="{% url 'student:add' %}">Student</a>

                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'photo1:album1_add' %}">Album</a>
                    <a class="dropdown-item" href="{% url 'photo1:photo1_add' %}">photo</a>
                    <a class="dropdown-item" href="{% url 'sugang:subject_add' %}">Subject</a>
                    <a class="dropdown-item" href="{% url 'sugang:apply_add' %}">Apply</a>
                </div>
            </li>


            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
                    <a class="dropdown-item" href="{% url 'blog:change' %}">Blog</a>
                    <a class="dropdown-item" href="{% url 'namecard:change' %}">Namecard</a>
                    <a class="dropdown-item" href="{% url 'student:change' %}">Student</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'photo1:album1_change' %}">Album</a>
                    <a class="dropdown-item" href="{% url 'photo1:photo1_change' %}">Photo</a>
                    <a class="dropdown-item" href="{% url 'sugang:subject_change' %}">Subject</a>
                    <a class="dropdown-item" href="{% url 'sugang:apply_change' %}">Apply</a>
                </div>



        </ul>

        <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
        </form>

        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </li>
        </ul>




    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>


{% block footer %}{% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/c998a172fe.js"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>Bookmark is a Uniform Resource Identifier (URI)
                that is stored for later retrieval in any of various storage formats.
                You can store your own bookmarks by Bookmark application.
                It's also possible to update or delete your bookmarks.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>Our premium profiles are for those who want to dive deeper into their personality and learn how to grow and better navigate the world around them.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shkim</div>
</footer>
{% endblock %}