blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

        # Example:/blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example:/blog/post/(sameas/blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example:/blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example:/blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example:/blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example:/blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example:/blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example:/blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example:/blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name="add"),
    path('change/', views.PostChangeLV.as_view(), name="change"),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(),name='register'),
    path('acounts/register/done/', UserCreateDoneTV.as_view(),name='register_done'),


    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('namecard/', include('namecard.urls')),
    path('student/', include('student.urls')),
    path('photo1/', include('photo1.urls')),
    path('sugang/', include('sugang.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #static함수는 정적파일을 처리하기위한 url패턴을 반환

photo1/urls.py
from django.urls import path
from photo1 import views


app_name = 'photo1'
urlpatterns = [

    # Example: /photo/
    path('', views.AlbumLV.as_view(), name='index'),

    # Example: /photo/album/, same as /photo/
    path('album1', views.AlbumLV.as_view(), name='album1_list'),

    # Example: /photo/album/99/
    path('album1/<int:pk>/', views.AlbumDV.as_view(), name='album1_detail'),

    # Example: /photo/photo/99/
    path('photo1/<int:pk>/', views.PhotoDV.as_view(), name='photo1_detail'),

    # Example: /photo/album/add/
    path('album1/add/', views.AlbumPhotoCV.as_view(), name='album1_add'),

    # Example: /photo/album/change/
    path('album1/change/', views.AlbumChangeLV.as_view(), name='album1_change'),

    # Example: /photo/album/99/update/
    path('album1/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album1_update'),

    # Example: /photo/album/99/delete/
    path('album1/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album1_delete'),

    # Example: /photo/photo/add/
    path('photo1/add/', views.PhotoCV.as_view(), name='photo1_add'),

    # Example: /photo/photo/change/
    path('photo1/change/', views.PhotoChangeLV.as_view(), name='photo1_change'),

    # Example: /photo/photo/99/update/
    path('photo1/<int:pk>/update/', views.PhotoUV.as_view(), name='photo1_update'),

    # Example: /photo/photo/99/delete/
    path('photo1/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo1_delete'),

]

photo1/models.py
from django.db import models
from django.urls import reverse
from photo1.fields import ThumbnailImageField


class Album1(models.Model):
    name = models.CharField('NAME', max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo1:album_detail', args=(self.id,))


class Photo1(models.Model):
    album = models.ForeignKey(Album1, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField('IMAGE', upload_to='photo1/%Y/%m') #upload_to 이미지가 저장될 폴더
    upload_dt = models.DateTimeField('UPLOAD DATE', auto_now_add=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)


    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo1:photo1_detail', args=(self.id,))

photo1/forms.py
from django.forms import inlineformset_factory
from photo1.models import Album1, Photo1

PhotoInlineFormSet = inlineformset_factory(Album1, Photo1, fields=['image', 'album', 'description'], extra=2)

photo1/views.py
from django.views.generic import ListView, DetailView
from photo1.models import Album1, Photo1

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from mysite.views import OwnerOnlyMixin
from photo1.forms import PhotoInlineFormSet


class AlbumLV(ListView):
    model = Album1
    template_name = 'photo1/album1_list.html'


class AlbumDV(DetailView):
    model = Album1
    template_name = 'photo1/album1_detail.html'


class PhotoDV(DetailView):
    model = Photo1
    template_name = 'photo1/photo1_detail.html'

# 이하추가
# #---Create/Change-list/Update/Delete for Photo


class PhotoCV(LoginRequiredMixin, CreateView):
    model = Photo1
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo1:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo1
    template_name = 'photo1/photo1_change_list.html'

    def get_queryset(self):
        return Photo1.objects.filter(owner=self.request.user)


class PhotoUV(OwnerOnlyMixin, UpdateView):
    model = Photo1
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo1:index')


class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo1
    success_url = reverse_lazy('photo1:index')

#이하추가
# #---Change-list/Delete for Album


class AlbumChangeLV(LoginRequiredMixin, ListView):
    model = Album1
    template_name = 'photo1/album1_change_list.html'

    def get_queryset(self):
        return Album1.objects.filter(owner=self.request.user)


class AlbumDelV(OwnerOnlyMixin, DeleteView):
    model = Album1
    success_url = reverse_lazy('photo1:index')


#---(InlineFormSet) Create/Update for Album


class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album1
    fields = ('name', 'description')   #어떤 컬럼을 폼에 채울지.
    success_url = reverse_lazy('photo1:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()   #앨범 레코드 생성.
            formset.instance = self.object #포토의 앨범컬럼에 앪범레코드의 id값을 설정
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class AlbumPhotoUV(OwnerOnlyMixin, UpdateView):
    model = Album1
    fields = ('name', 'description')
    success_url = reverse_lazy('photo1:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

photo1/templates/photo1/album1_change_list.html
{% extends "base.html" %}
{% block title %}album_change_list.html{% endblock %}
{% block content %}

    <h1>Album Change -{{user}}</h1>
    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="table-success">
            <th>Name</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo1:album1_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo1:album1_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

photo1/templates/photo1/album1_confirm_delete.html
{% extends "base.html" %}
{% block title %}album_confirm_delete.html{% endblock %}
{% block content %}
    <h1>Album Delete <small class="font-italic">(including related photos)</small></h1>

    <br>
    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}

photo1/templates/photo1/album1_detail.html
{% extends "base.html" %}
{% block title %}album_detail.html{% endblock %}
{% block extra-style %}
<style>
.thumbnail {
border: 5px solid #ccc;
}</style>

{% endblock %}
{% block content %}
    <div class="mt-5">
        <span class="h2">{{ object.name }}&emsp;</span>
        <span class="h5 font-italic">{{ object.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">
    <div class="row"> {% for photo1 in object.photo1_set.all %}
        <div class="col-md-3 mb-5">
            <div class="thumbnail">
                <a href="{{ photo1.get_absolute_url }}">
                    <img src="{{ photo1.image.thumb_url }}" style="width: 100%;">
                </a>
            </div>

            <ul>
                <li class="font-italic">{{ photo1.title }}</li>
                <li class="font-italic">{{ photo1.upload_dt|date:"Y-m-d" }}</li>
            </ul>
        </div>
        {% endfor %}
    </div>

{% endblock %}

photo1/templates/photo1/album1_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}album_form.html{% endblock %}

{% block content %}
    <h1>Album-Photo Create/Update -{{user}}</h1>
    <p class="font-italic">This is a creation or update form for your album using PhotoInlineFormSet.</p>
    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    {% if formset.errors %}
    <div class="alert alert-warning">
        <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
        {% for formerrors in formset.errors %}
            {{ formerrors }}
        {% endfor %}
    </div>
    {% endif %}

    {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" action="" method="post">
    {% else %}
    <form action="." method="post">
    {% endif %}
    {% csrf_token %}

    <h4>create or update album contents</h4>
    <fieldset class="card pt-3">
        <div class="form-group row">
            {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.name|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control" }}
            </div>
        </div>
    </fieldset>
    <br>

    <h4>create or update photo contents</h4>
    <fieldset class="card pt-3">
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.id }}
            {# form.album #}
        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control"|attr:"rows:3" }}
            </div>
        </div><hr>{% endfor %}
    </fieldset>
        <div class="form-group card py-1">
            <div class="offset-sm-3 col-sm-5"><input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>
    </form>
{% endblock %}

photo1/templates/photo1/album1_list.html
{% extends "base.html" %}
{% block title %}album_list.html{% endblock %}
{% block extra-style %}

<style>
.thumbnail {
border: 3px solid #ccc;
}
</style>

{% endblock %}

{% block content %}

    {% for item in object_list %}
    <div class="mt-5">
        <a class="h2" href="{% url 'photo1:album1_detail' item.id %}">
            {{ item.name }}</a>&emsp;
        <span class="font-italic h5">{{ item.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">

    <div class="row">
        {% for photo1 in item.photo1_set.all|slice:":5" %}
        <div class="ml-5">
            <div class="thumbnail">
                <a href="{{ photo1.get_absolute_url }}">
                    <img src="{{ photo1.image.thumb_url }}" style="width: 100%;">
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% endblock %}

photo1/templates/photo1/photo1_change_list.html
{% extends "base.html" %}
{% block title %}photo_change_list.html{% endblock %}
{% block content %}
    <h1>Photo Change -{{user}}</h1>
    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="table-info">
            <th>Album</th>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.album }}</td>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo1:photo1_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo1:photo1_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

photo1/templates/photo1/photo1_confirm_delete.html
{% extends "base.html" %}
{% block title %}photo_confirm_delete.html{% endblock %}
{% block content %}
<h1>Photo Delete</h1>
<br>
<form action="." method="post">{% csrf_token %}<p>
    Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
</form>
{% endblock %}

photo1/templates/photo1/photo1_detail.html
{% extends "base.html" %}
{% block title %}photo_detail.html{% endblock %}
{% block content %}

    <h2 class="mt-5">{{ object.title }}</h2>
    <div class="row">
        <div class="col-md-9">
            <a href="{{ object.image.url }}">
                <img src="{{ object.image.url }}" style="width: 100%;">
            </a>
        </div>

        <ul class="col-md-3 mt-3">
            <li class="h5">Photo Description</li>
            {% if object.description %}<p>{{ object.description|linebreaks }}</p>
            {% else %}<p>(blank)</p>{% endif %}

            <li class="h5">Date Uploaded</li>
                <p class="font-italic">{{ object.upload_dt }}</p>
            <li class="h5">Album Name</li>
                <p class="font-italic">
                    <a href="{% url 'photo1:album1_detail' object.album.id %}"> {{ object.album1.name }}</a>
                </p>
        </ul>
    </div>

{% endblock %}

photo1/templates/photo1/photo1_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}photo_form.html{% endblock %}
{% block content %}
    <h1>Photo Create/Update -{{user}}</h1>
    <p class="font-italic">This is a creation or update form for your photo.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    {% if form.is_multipart %}
    <form enctype="multipart/form-data" action="" method="post" class="card pt-3">{% csrf_token %}
    {% else %}
    <form action="." method="post" class="card pt-3">{% csrf_token %}
    {% endif %}



        <div class="form-group row">
            {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-2">
                {{ form.album|add_class:"form-control" }}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'photo1:album1_add' %}" class="btn btn-outline-primary btn-sm">Add Album</a>
            </div>
        </div>

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

         <div class="form-group row">
              {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
              <div class="col-sm-8">
                 {{ form.description|add_class:"form-control"|attr:"rows:3" }}
             </div>
         </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
             </div>
        </div>
    </form>
{% endblock %}